[package]
name = "rkit"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2021"
readme = "README.md"
homepage = "https://github.com/Nazariglez/rkit"
repository = "https://github.com/Nazariglez/rkit"
license = "MIT OR Apache-2.0"
description = ""

[profile.release]
# optimize for speed and size
opt-level = 2
# link time optimization
lto = true
# remove debug symbols
strip = true
# do not parallelize optimizations
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["crates/*"]

[workspace.dependencies]
# gamekit packages
corelib = { path = "crates/corelib" }
utils = { path = "crates/utils" }
draw = { path = "crates/draw" }
macros = { path = "crates/macros" }
audio = { path = "crates/audio" }
assets = { path = "crates/assets" }

## common deps
log = "0.4.22"
raw-window-handle = "0.6.2"
atomic_refcell = "0.1.13"
serde = { version = "1.0", features = ["serde_derive"] }
rkyv = "0.8.0-alpha.3"
heapless = "0.8.0"
arrayvec = "0.7.6"
nohash-hasher = "0.2.0"
smol_str = "0.3.1"
lazy_static = "1.5.0"
bytemuck = "1.17.1"
smallvec = "2.0.0-alpha.7"
once_cell = "1.19.0"
rayon = "1.10.0"
hashbrown = "0.15.0"
rustc-hash = "2.0.0"
num = "0.4.3"
parking_lot = "0.12.3"
web-sys = "0.3.72"
js-sys = "0.3.72"
wasm-bindgen = "0.2.95"

[dependencies]
corelib.workspace = true
utils.workspace = true
draw = { workspace = true, optional = true }
audio = { workspace = true, optional = true }
assets = { workspace = true, optional = true }

log.workspace = true

fastrand = { version = "2.1.1", optional = true }

# used on filters TODO maybe this must be optional under the filter feature?
atomic_refcell.workspace = true
once_cell.workspace = true
arrayvec.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
fastrand = { version = "2.1.1", optional = true, features = ["js"] }

[dev-dependencies]
log.workspace = true
bytemuck = {workspace = true, features = ["derive"]}
shipyard = "0.7.2"
static_assertions = "1.1.0"

[features]
default = ["random", "draw", "draw-default-font", "audio", "assets", "logs"]
# enable loggin
logs = ["corelib/logs"]
# enables gamepad api
gamepad = ["corelib/gamepad"]
# force webgl
webgl = ["corelib/webgl", "draw/webgl"]
# enable fastrand random
random = ["dep:fastrand"]
# enables draw API
draw = ["dep:draw"]
# enables audio API
audio = ["dep:audio"]
# enabels async assets loading
assets = ["dep:assets"]
# included a default font
draw-default-font = ["draw?/default-font"]