[package]
name = "utils"
edition = "2021"

[dependencies]
hashbrown.workspace = true
rustc-hash.workspace = true
arrayvec.workspace = true
once_cell.workspace = true

paste = "1.0.15"
lru = { version = "0.12.5" , default-features = false }