[package]
name = "audio"
edition = "2024"

[dependencies]
corelib.workspace = true

# Kira does include by default "mp3" and "flac" features,
# however mp3 have license issues and flac is too big/not needed for our case
kira = { version = "0.12.3", default-features = false, features = ["cpal", "ogg", "vorbis", "wav", "pcm"] }

# common deps
log.workspace = true
once_cell.workspace = true
atomic_refcell.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
num.workspace = true

