[package]
name = "core"
edition = "2021"
build = "build.rs"

[dependencies]
# gk dependencies

# external common deps
log.workspace = true
nohash-hasher.workspace = true
heapless.workspace = true
atomic_refcell.workspace = true
arrayvec.workspace = true
smol_str.workspace = true

# app/windowing
winit = "0.30.5"

# math
glam = "0.29.0"

# gfx
pollster = "0.3.0"
wgpu = "22.1.0"

# gamepad
gilrs = "0.10.9"

## deps only for this crate
once_cell = "1.19.0"
bitflags = "2.6.0"
strum = "0.26.3"
strum_macros = "0.26.4"
smallvec = "2.0.0-alpha.7"
crossbeam-channel = "0.5.13"

[features]
# Hackish, to add environment variables for test builds
test-env = []

[dev-dependencies]
# Hackish, to add environment variables for test builds
core = { path = ".", features = ["test-env"]}